import "@ant-design/v5-patch-for-react-19";
import "./globals.css";
import { UserState } from "@/context/UserContext";
export const metadata = {
  title: "JobScamShield",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserState>
        <body>{children}</body>
      </UserState>
    </html>
  );
}
