name: JobScamShield Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fake-job-posting:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: |
            <?xml version="1.0" encoding="utf-8"?>
            <publishData>
              <publishProfile
                profileName="${{ secrets.AZURE_WEBAPP_NAME }}"
                userName="${{ secrets.AZURE_WEBAPP_USERNAME }}"
                userPWD="${{ secrets.AZURE_WEBAPP_PASSWORD }}"
                siteName="${{ secrets.AZURE_WEBAPP_NAME }}"
              />
            </publishData>
